### PR TITLE
delete temp files after viewing them

### PR DESCRIPTION
**Pull request by omar-polo**
Hi!

tut leaves quite a few temporary files in /tmp, let's get rid of them.

### CODE REVIEW

**Comment by omar-polo** [comment]
There's something wrong with the diff?  Should I have created a relative issue too?

**Comment by RasmusLindroth** [comment]
I'll have a look at this when I get time. But I'm a bit skeptical about

```go
for _, ext := range external {
	exec.Command(ext.Name, ext.Args...).Run()
	deleteFiles(filenames) // this line
}
```

As it potentially could delete files before they have been opened. I think I'll add a function to the `runProgram` struct instead so you can delete each file separately, maybe with a timer so it won't interfere with the program opening the file.

**Comment by omar-polo** [comment]
Sorry, I didn't meant to be pushy, i was just wondering if I was missing something in how I filed the diff.

> As it potentially could delete files before they have been opened.

I thought it 's safe because `Cmd.Run()` also waits for the command to complete.  The only way it could break it's if said program forks in the background without opening the files first, but I'd consider it a bug in the viewer and not in tut (also, at that point, even the choice of the timer because bogus, it could always open the files after the timer expires for $reasons.)  FWIW I've tested it with mpv, nsxiv and gpicview.

Thanks!

**Comment by RasmusLindroth** [comment]
>Sorry, I didn't meant to be pushy, i was just wondering if I was missing something in how I filed the diff.

No worries! I just meant that I haven't looked at the code all that much :)

>I thought it 's safe because Cmd.Run() also waits for the command to complete. The only way it could break it's if said program forks in the background without opening the files first, but I'd consider it a bug in the viewer and not in tut (also, at that point, even the choice of the timer because bogus, it could always open the files after the timer expires for $reasons.) FWIW I've tested it with mpv, nsxiv and gpicview.

But let's say we have three files in `filenames`. When the first file calls `Cmd.Run()` it runs `deleteFiles(filenames)`. Wouldn't file two and three already have been deleted when the loop reaches them? At least if you have set `image-single=true` in your config.

Or am I too tired to think?

**Comment by omar-polo** [comment]
No, you're right and I misunderstood your first comment, apologise.  I only tested with `image-single=false` and haven't thought about the case with it being `true`.

An easy change would be to just move the `deleteFiles`  after the for completes, so we delete the files only when all are deleted.

**Comment by omar-polo** [comment]
Thank you! :)

**Comment by RasmusLindroth** [comment]
And thank you :)

**Comment by benjaminbhollon** [comment]
Working like a charm for me in the new release. :)

**Pull request merged**
